name: Deploy and Verify Webhook Handler

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies if needed
        run: |
          if [ -f package.json ]; then
            if [ ! -f yarn.lock ]; then
              yarn install
            fi
          elif [ -f yarn.lock ]; then
            yarn install
          else
            echo "No package.json or yarn.lock found!"
            exit 1
          fi

      - name: Set Environment Variables
        run: |
          echo "MONNIFY_API_KEY=${{ secrets.MONNIFY_API_KEY }}" >> $GITHUB_ENV
          echo "MONNIFY_SECRET_KEY=${{ secrets.MONNIFY_SECRET_KEY }}" >> $GITHUB_ENV
          echo "FIREBASE_ADMIN_SDK=${{ secrets.FIREBASE_ADMIN_SDK }}" >> $GITHUB_ENV

      - name: Build project
        run: yarn build

      - name: Check for changes before deploying
        run: |
          git diff --quiet || echo "CHANGES_DETECTED=true" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages (if changes detected)
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Deploy to GitHub Pages' || exit 0
          git push --force origin HEAD:gh-pages

      - name: Run Verification Script
        run: yarn verify
